### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#1]
Hi, great extension.
Can you put more information/examples for configuration.
Whan I press f6 I have this error:
_command 'oradew.compileTask' not found_

**Comment by mickeypearce** [comment]
Hi, thanks for your feedback. :grinning: 

You start up workspace with "Initialize Workspace/Version" command that creates configuration file (oradewrc.json) in your working folder. 

Can you please try to do that if you haven't already done so.

**Comment by Danieleeee** [comment]
I have this error:
`You must have 64-bit Oracle client libraries in your PATH environment variable.`
What name should I give to the variable?

**Comment by mickeypearce** [comment]
If you have a 32-bit Oracle driver, please make sure that your Node.js is also 32-bit (ia32) if that is possible. Oracle driver in extension is currently precompiled for this architecture.

**Comment by Danieleeee** [comment]
I have 64bit oracle driver and Node.js

**Comment by mickeypearce** [comment]
I will post a 64-bit version ASAP. 
Could you please tell me your OS details (version/arch)?

**Comment by Danieleeee** [comment]
I have error when I try npm rebuild:

> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
> gyp ERR! stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:166:19)
> gyp ERR! stack     at Object.onceWrapper (events.js:255:19)
> gyp ERR! stack     at ClientRequest.emit (events.js:160:13)
> gyp ERR! stack     at Socket.socketOnData (_http_client.js:469:11)
> gyp ERR! stack     at Socket.emit (events.js:160:13)
> gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
> gyp ERR! stack     at readableAddChunk (_stream_readable.js:256:11)
> gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:213:10)
> gyp ERR! stack     at TCP.onread (net.js:599:20)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\dricci\.vscode\extensions\mp.oradew-vscode-0.0.2\node_modules\oracledb
> gyp ERR! node -v v9.4.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! oracledb@2.1.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the oracledb@2.1.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Danieleeee** [comment]
Can you integrate this extension with [sqlTools](https://github.com/mtxr/vscode-sqltools) that works fine with others DB, or [plsql-language](https://github.com/zabel-xyz/plsql-language)?

**Comment by mickeypearce** [comment]
If you are behind a proxy you should set it correctly.
```
npm config set proxy http://my-proxy.example.com:80/
npm config set https-proxy http://my-proxy.example.com:80/
npm rebuild
```
from [Error: tunneling socket could not be established,...](https://stackoverflow.com/questions/33162560/error-tunneling-socket-could-not-be-established-cause-connect-econnrefused-10)
or
```
set http_proxy=http://my-proxy.example.com:80/
set https_proxy=http://my-proxy.example.com:80/
npm install
```
from [Installing node-oracledb Version 2](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin)

**Comment by Danieleeee** [comment]
I use a proxy, but it is correctly set up and works for other extensions.
Thanks

**Comment by mickeypearce** [comment]
Yeah, but this ext is a special one...

**Comment by Danieleeee** [comment]
These are some select that can be used:

`function describeTable(err, connection) {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      'Select *
      from dba_tables
     where upper(table_name) like upper(:table_name)
       and owner in (:user_owner)',
      ['%siu%serv%sogg%','UTE'],  // bind value
      function(err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        console.log(result.rows);
        doRelease(connection);
      }
    );
  }`

`function columnInformation(err, connection) {
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      ' Select *  
          from dba_tab_columns 
        where upper(TABLE_NAME) = upper(:table_name)
          and upper(COLUMN_NAME) = upper(':column_name')
          and owner = :user_owner',
      ['SIU_sii_RICHIESTe','stato','UTE'], 
      function(err, result) {
        if (err) {
          console.error(err.message);
          doRelease(connection);
          return;
        }
        console.log(result.rows);
        doRelease(connection);
      }
    );
  } `

**Comment by Danieleeee** [comment]
Hi,
finally I recompiled (npm rebuild) the extension in 64 bit.
Now I have this error:

> TypeError: require.extensions.hasOwnProperty is not a function
>     at requireDir (C:\Users\dricci\.vscode\extensions\mp.oradew-vscode-0.0.2\node_modules\require-dir\index.js:93:37)
>     at Object.<anonymous> (C:\Users\dricci\.vscode\extensions\mp.oradew-vscode-0.0.2\node_modules\gulp-git\index.js:4:18)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Users\dricci\.vscode\extensions\mp.oradew-vscode-0.0.2\out\config\utils\git.js:2:13)

**Comment by Danieleeee** [comment]
I use node version 9.4.0
require.extensions.hasOwnProperty is deprecated

**Comment by Danieleeee** [comment]
I updated "gulp-git": "^2.5.2" in package.json and it seems to work

**Comment by mickeypearce** [comment]
Thanks a lot for putting effort into it and making it work for 64-bit. I upgraded the gulp-git dependency.
