### ISSUE TITLE
Support for different configs per environment

### ISSUE THREAD

**Issue by jasonchester** [mickeypearce/oradew-vscode#10]
Would like to pass different template variables per environment in to the scripts.

My use case is for a custom SEND_MAIL package.

`v_email_server	VARCHAR2(30) := '${config["version.number"]}';`

**Comment by mickeypearce** [comment]
Hey @jasonchester!

I could make it `oradewrc.json` to be the base configuration and then optional configurations for environments (`oradewrc.test.json`, `oradewrc.uat.json`).

For example:
`oradewrc.json`:
```
{
...
...
  "customField": "this is it."
}
```
and 
`oradewrc.test.json`:
```
{
  "customField": "..no this."
}
```
would overload base configuration for TEST environment variables.
(We also need `TEST: Package` and `UAT: Package` command for your use-case).

**Comment by jasonchester** [comment]
Yes, this would be perfect. I like the file per environment approach as opposed to the prefixed variables because it is easier to work with.
* Easier a source control versioning
* Easier to compare environment settings with diff tooling
* Similiar to how other systems have implemented env configs ie. dotnet core

As far as the new environment based packaging commands, i am wondering if it would be better if oradew implemented a [**Task Provider**](urlhttps://code.visualstudio.com/docs/extensions/example-tasks#_task-provider) which could parse the dbconfig.json and generate task definitions for each one defined.

Thanks again.

**Comment by mickeypearce** [comment]
I was actually thinking about Task provider approach just recently...

One disadvantage would be, that you can not dynamically bind extension commands to Command palette or UI, as far as I know, but you have to add them manually to extension's `package.json` file. So dynamically loaded tasks with provider could not be executed as commands as it is done now.

**Comment by mickeypearce** [comment]
Environment-specific file configs are now available. @jasonchester, you can try them out.

About implementing task provider for oradew commands, I suggest opening maybe a new issue for the request...
