### ISSUE TITLE
Externalize gulp script and provide better documentation on its usage

### ISSUE THREAD

**Issue by jasonchester** [mickeypearce/oradew-vscode#11]
I would like to use the gulp script outside of the vscode extension. 

Would it be possible to publish an Azure DevOps Plugin as well as a vscode extension.

There are a number of use cases this would enable for me.
* Automating the creation of multiple git based oradew database projects
* Implementing a devops pipeline for deployment of oracle databases
* Implementing a system that monitors development databases for changes and stores them in source control 

@mickeypearce  Love your extension btw, great job filling the gaping hole of opensource oracle development tooling.

**Comment by mickeypearce** [comment]
Externalization of gulp script (tasks) into a gulp plugin would enable you to use it outside of vscode. 

It is not really planned at the moment but it's a nice idea. Maybe in the future...

**Comment by mickeypearce** [comment]
I exposed oradew commands (gulp tasks) in command line (CLI). It is not super polished but it's a start. :pregnant_woman: 

```
$ git clone https://github.com/mickeypearce/oradew-vscode (or go to ext folder ~/.vscode/extensions/mp.oradew-vscode-...)
# Installation
$ npm run install-cli
# (Use `oradew <command> --help` for command options.)
$ oradew --help
Usage: oradew <command> [options]

Commands:
  initWorkspace            Initialize Workspace
  createSource [options]   Import All Objects from Db to Source
  compileFiles [options]   Compile files (all source if no file specified)
  compileObject [options]  Compile selected object
  importFiles [options]    Import files (all source if no file specified)
  importObject [options]   Import selected object
  package [options]        Package
  runFile [options]        Run file as a Script (path package.deploy if no file specified)
  runTest [options]        Run unit tests
```
