### ISSUE TITLE
Keybinding conflict with powershell

### ISSUE THREAD

**Issue by jasonchester** [mickeypearce/oradew-vscode#12]
the keybinding F8 is overriding they powershell module's keybinding for F8.

The extension should configure appropriate keybinding when conditions to prevent conflicts like this.
- https://stackoverflow.com/questions/44852670/adding-conditions-to-when-from-vs-code-extension
- https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

I see that there are activation events defined for the module already but it appears these that keybindings are applied even if the extension is not activated.

**Comment by mickeypearce** [comment]
I actually planned f8 keybingind removal in the next version. It conflicts with vscode command: "Go To Next Problem" wich is a very useful command.

For now you can remove it with:
`keybindings.json`
```
// To remove the second rule, for example, add in keybindings.json:
{ "key": "f8", "command": "-oradew.packageTask" }
```

**Comment by mickeypearce** [comment]
Thanks for the links. I will look into properly activating keybindings for project only.

**Comment by mickeypearce** [comment]
- Removed `F7` (`Run tests`) and moved `F8` (`Package`) to `F9` because of conflicts
- Fixed keybindings activations

@jasonchester thanks again for the links. Really useful! 👍
