### ISSUE TITLE
Update node-oracledb version.

### ISSUE THREAD

**Issue by jasonchester** [mickeypearce/oradew-vscode#15]
When installing on Windows with 
**node-v10.15.1-x64.msi** and
**instantclient-basiclite-windows.x64-18.3.0.0.0dbru.zip** 

`npm rebuild` fails with a download error.

Can you please update the node-oracledb dependency to 3.1 which I believe fixes the download issue?

Thanks,
Jason

**Comment by mickeypearce** [comment]
Hey @jasonchester. 

I upgraded node-oracledb to v3.1.1 as you suggested. The latest oradew version is v0.2.1.

This version includes pre-built binaries for Node 6, 8, 10 and 11 for Win (x64), macOS (Intel x64) and Linux (x86-64). `npm rebuild` is not longer needed if you work on those environments. :+1: 

Node 9 is not included anymore as it was previously bundled into oradew (node-oracedb@2.2.0).
