### ISSUE TITLE
Import DB object metadata

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#2]
Hi,
Importing DB objects locally is a nice idea, especially if I want to work with the extension "Language PL/SQL".

The problem is that I have a large DB and it takes me a long time to import all the objects. In addition I need a lot of space on the local disk.
How can I solve the problem?
Thanks

**Comment by mickeypearce** [comment]
If you have objects/files in your schema that are not part of your current project you can simply delete them from workspace src directory. 
You can then use 'Import changes from DB' command to update only src objects/files that are left in your workspace.

**Comment by mickeypearce** [comment]
Hey @Danieleeee, is this "Import Changes" command helpful?

**Comment by Danieleeee** [comment]
Yes, but it is not fundamental. 
In some cases it can be an inconvenient constraint for compiling packages.
It would be more useful to have the suggestion of the names of the tables, columns and packages when you start typing their name inside a package or a select.

**Comment by Danieleeee** [comment]
I can (if you want) get you and test the select necessary to get such information from the Oracle DB

**Comment by Danieleeee** [comment]
I imagined you would have given me this answer :(
The problem is that the other extensions, like "Language PL/SQL"  or "sql tools", are set up to do what I have required, but the developers are not as practical as you in oracleDB module.
I believe that with your little intervention on their extensions could make them capable of doing what is required.
Or you can copy their code and insert it in this extension.

**Comment by mickeypearce** [comment]
The biggest challenge in adding Oracle support is node-oracledb being a native module which complicates the installation process of the extension.
Oradew unfortunately doesn't solve that. :(

**Comment by Danieleeee** [comment]
you are referring to npm recompile for the 64bit?

**Comment by mickeypearce** [comment]
Yes, electron rebuild. I will look into it...

**Comment by mickeypearce** [comment]
Opened PR: https://github.com/mtxr/vscode-sqltools/pull/88.

**Comment by Danieleeee** [comment]
Hi @mickeypearce ,
can you add this [enancement](https://github.com/zabel-xyz/plsql-language/issues/32#issuecomment-391701896)?

Thanks

**Comment by mickeypearce** [comment]
@Danieleeee, you can save a select statement to a function and use Code Generator (`Generate`) to populate the file.

Configure:
```
"generator.define": [
    {
      "label": "Import autocompletion",
      "function": "proc_myImportAutocomplete",
      "description": "Import autocompletion file",
      "output": ".vscode/plsql.completion.json"
    }
  ]
```

and then "Generate..." ...
