### ISSUE TITLE
ORADEW Doesn't Import Anything

### ISSUE THREAD

**Issue by sspringer** [mickeypearce/oradew-vscode#20]
This is pretty straight-forward, but it's only happening on one of my schemas.

I am attempting to import the existing tables, sequences, triggers, and packages from a fairly new schema that I'm working in.  When I attempt to run the command "Import All Source from DB", the command runs and completes but nothing seems to be happening.  

To be specific, I get all of the default folders created - scripts, src, and test, with the functions, package bodies, packages, etc... sub folders under src - but none of the actual database objects that are currently in there are having their DDL populated into the appropriate folder.

I'm not getting any sort of error messages or, well, anything when I run the command.  It just completes.

Any ideas?

**Comment by mickeypearce** [comment]
Could it be that you connect with the "user" that is not the owner of the objects? 

Oradew uses data from the following select to create file structure:

https://github.com/mickeypearce/oradew-vscode/blob/13f9056b778256b3455dc4af6762de5c72ed5285/src/common/db.js#L236-L242

with :objectType = 'TABLE' (for tables, etc.), :objectName = null and :owner = connection user defined in dbconfig.json.

Please try quering in your DB to se actual owner:
```
select  *     
from all_objects; 
```
Thanks for your feedback!

**Comment by sspringer** [comment]
Thanks for the quick response.

If I run the following query:

    select 
        owner, 
        object_id, 
        object_name, 
        object_type, 
        cast(last_ddl_time as timestamp) as last_ddl_time, 
        status 
    from 
        all_objects 
    where 
        upper(owner) = upper('**********')  -- ********** is replaced with the actual schema user name
    and 
        upper(object_type) = upper(nvl(null, object_type)) 
    and 
        upper(object_name) = upper(nvl(null, object_name)) 
    and 
        object_name not like 'SYS_PLSQL%' 
    order by 
        object_id

I get back 14 records.  Here's a summary of some of that data:

| Owner | Object ID | Object Name | Object Type | Last DDL Time | Status |
| ---------- | -------- | ------------ | ------------ | --------------------------------- | ------- |
| ********** | 260821 | MY_TABLE | TABLE | 25-APR-19 09.36.50.000000000 AM | VALID |
| ********** | 260822 | MY_INDEX | INDEX | 22-APR-19 01.23.47.000000000 PM | VALID |
| ********** | 260830 | MY_SEQUENCE | SEQUENCE | 22-APR-19 02.49.18.000000000 PM | VALID |
| ********** | 260831 | MY_TRIGGER | TRIGGER | 22-APR-19 03.09.49.000000000 PM | VALID |
| ********** | 260833 | MY_PKG_DEV | PACKAGE | 01-MAY-19 01.18.11.000000000 PM | VALID |
| ********** | 260834 | MY_PKG_BODY | PACKAGE BODY | 07-MAY-19 01.10.29.000000000 AM | VALID |

Obviously I've changed the owner and object names to keep from publicizing them on the interwebs.

I think the ownership is set up correctly.  The user I've hidden here is the same user as I have set up in the dbconfig.json, and the password I have set up in that file is the same one that I use to log into the development DB with.

Is there any sort of verbose/debugging mode that I can turn on?

**Comment by mickeypearce** [comment]
There is a "oradew.chatty" config but unfortunatelly it won't help in this scenario I am afraid.

Tomorrow I can make a custom release with some debuging outputs to print the actual sql executed, maybe it would help...

You are not messing with "source.input" parameter in oradewrc.json, that is the only thing It could mess with creating files from objects - by design at least 🤔 

https://github.com/mickeypearce/oradew-vscode/blob/13f9056b778256b3455dc4af6762de5c72ed5285/src/gulpfile.js#L599-L600

**Comment by sspringer** [comment]
No, I installed in and ran it.  I don't remember messing with any part of the configuration, but I'll check just to be safe.

I used it once on a previous project and it worked like a champ.  This time it just won't import the schema.

The schema user doesn't need to be granted any specific rights, does it?

**Comment by mickeypearce** [comment]
No, not really. If a select from `all_objects` returns data, that should be it.

**Comment by mickeypearce** [comment]
Actually it was a bug. :disappointed: I released a fix (0.3.8) version, please confirm it works for you. Thanks again for reporting.

**Comment by sspringer** [comment]
I've been pulled away from this project for a couple of days and I'm just getting back on this now.  I'm going to install this update now and let you know how it goes.

Thanks!

**Comment by sspringer** [comment]
It worked!  Thanks for the quick attention to this issue!
