### ISSUE TITLE
Wrong encoding after import sources.

### ISSUE THREAD

**Issue by otherexception** [mickeypearce/oradew-vscode#21]
I've tried to import all source from db, but i can't change the encoding of imported files. My db encoding is WIN1250 whereas Imported files are encoded in UTF8. How to change it? Property "package.encoding" doesn't change anything in this case.

**Comment by mickeypearce** [comment]
Yes, ` "package.encoding"` changes only encoding of packaged script (`deploy/run.sql`). 

I had a problem converting to win1250 when exporting (Node.js  related - not remembering exacatly what was the problem) and then settled for UTF-8 for files,  but allowing encoding setting  for deploy package (`"package.encoding": "win1250"`) which can then be executed with Oracle tools: SQLPlus, SQL Developer.

Can you tell me what exactly is your problem or what are you trying to achieve. In other words why not have files in UTF-8? :smile:

**Comment by otherexception** [comment]
Mainly I have problem with importing source of packages which contains a lot comments with polish characters and after conversion to uft8 they are unreadable (after compile for another users as well).

**Comment by mickeypearce** [comment]
Can you please provide a simple example: a text with characters that cause problem, so I can reproduce?

**Comment by otherexception** [comment]
Comment (NLS_LANG=POLISH_POLAND.EE8MSWIN1250):
// Zażółć gęślą jaźń

**Comment by mickeypearce** [comment]
I saved your comment in a DB proc and imported and the characters came intact. I also have an NLS_CHARACTERSET=EE8MSWIN1250

Can you check if your imported .sql file is opened with "UTF-8" encoded? (righ-bottom corner of editor)
![image](https://user-images.githubusercontent.com/1925433/57678168-ed173000-7628-11e9-9f9e-3fbd5da08873.png)

**Comment by otherexception** [comment]
I've tested it, and it works. but now I have to convert all my scripts to uft-8.

**Comment by mickeypearce** [comment]
You are right. I will release a new version today with `source.encoding` parameter, that lets you specifiy the source files encoding.

**Comment by mickeypearce** [comment]
@otherexception , I just released a 0.3.9 version with `"source.encoding"` setting.

Adding `"source.encoding": "win1250"` to `oradewrc.json` should export files in win1250. (default is utf8, similar to package.encoding)

I also use  `"files.encoding": "windows1250"` in `settings.json` so files are definitely opened in correct encoding, just in case.

**Comment by mickeypearce** [comment]
better setting:
```
"[plsql]": {
    "files.encoding": "windows1250"
  }
```
