### ISSUE TITLE
Ctrl-Enter doesnt seem to be working

### ISSUE THREAD

**Issue by hpanch** [mickeypearce/oradew-vscode#24]
When I do Ctrl+Enter on a SQL statement, it give an error {"error":"No params !"} 

The only way i am able to run the statement is to select it and then "Run Selected Statement" - when you have a large SQL statement to run and there are multiple statements in a single file, this becomes quite a chore.  Is there some kind of setting that I need to have?

**Comment by mickeypearce** [comment]
hey @hpanch ,

Thanks for the request. I will improve executing statement without the need of selecting the actual query...

**Comment by yevon** [comment]
I'm developing this one. Now I have finished the selection of first select statement in the worksheet, but now I have to implement just to select the nearsest one to the cursor and other statement compatibility.

**Comment by mickeypearce** [comment]
Top! If you would like to discuss something or similar just open a PR whenever.
