### ISSUE TITLE
Catalina upgrade causes error on task compiler

### ISSUE THREAD

**Issue by rygo18** [mickeypearce/oradew-vscode#32]
I can't run the task runner to compile files after upgrading to Catalina.

![image](https://user-images.githubusercontent.com/6289751/68604094-9d170a00-04a1-11ea-9fe9-87d5e455b9b1.png)

I was getting this error everywhere before but re-installing SQLPlus has resolved it everywhere else e.g. in the terminal.
So, it is correctly set in my profile as the terminal in VS code works (below screenshot).

![image](https://user-images.githubusercontent.com/6289751/68604031-778a0080-04a1-11ea-8c3f-4d09bc513f6b.png)
 
Hopefully this is something as simple as permissions somewhere in the extensions that need to run external libraries (Catalina has enforced a lot of other permissions) but I'm a little lost with finding a solution.

**Comment by mickeypearce** [comment]
Can you post a full output from the terminal after you execute an Oradew command?

**Comment by mickeypearce** [comment]
Extension executes this on "Compile as script" command:
https://github.com/mickeypearce/oradew-vscode/blob/5be8035596536572da2e81c297d76db1abcbad71/src/common/base.js#L230

**Comment by rygo18** [comment]
Sorry, was excluding my db details :)
`
Command failed: (echo connect user/password@server/db & echo start myfile.bod & echo show errors) | "sqlplus" -S /nolog  
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
`

and this is what was executed by the task runner;  
`
Executing task in folder uuid: node /Users/me/.vscode/extensions/mp.oradew-vscode-0.3.14/node_modules/gulp/bin/gulp.js --cwd /Users/me/code_repo --gulpfile /Users/me/.vscode/extensions/mp.oradew-vscode-0.3.14/out/gulpfile.js --color true --silent true run --env DBNAME --file /Users/me/code_repo/myfile.bod <
`

**Comment by mickeypearce** [comment]
Can you try just this:
https://github.com/mickeypearce/oradew-vscode/blob/5be8035596536572da2e81c297d76db1abcbad71/src/common/base.js#L232

I added "show errors" back recently, maybe it fails to pipe multiple command... :confused:

**Comment by rygo18** [comment]
Same error, I'm afraid.
`
Command failed: exit | "sqlplus" -S user/password@server/db @"myfile.bod"
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
`

It's weird that I can call sqlplus from the terminal window in VS Code but the task runner can't, does it not point to the exact same instance of sqlplus on my machine?
It looks like Catalina removed my installation of oracleclient.

**Comment by mickeypearce** [comment]
It should be, but looks as if SQLplus gets executed in process without access to environment variables, for some reason.
 
You can try a workaround with .bat file similar to that made in #28, where you first set ORACLE_HOME...

Do you ever use "Compile Current File" command. Does that work?

**Comment by mickeypearce** [comment]
Sorry I got a bit confused, SQL Plus works from terminal or not?

**Comment by rygo18** [comment]
Yes, SQL Plus works just fine from the terminal directly and when I use the built in terminal in VS code. Also, your 'Run Selected Statement' command works just fine and returns rows from a table. 

However, another issue that seems new is that when I run "Compile Current File" it outputs "Success =>" but it's not catching errors that I deliberately added which my terminal is catching.  
I've always been running "Run Current File As Script" up until now.

**Comment by mickeypearce** [comment]
Pleaes check if you have path to your Oracle client in system PATH variable.

**Comment by rygo18** [comment]
@mickeypearce Yes, my path contains the bin library where my Oracle Client is. SQL Plus wouldn't work in the terminal otherwise, right?

**Comment by mickeypearce** [comment]
> Same error, I'm afraid.
> `Command failed: exit | "sqlplus" -S user/password@server/db @"myfile.bod" Error 6 initializing SQL*Plus SP2-0667: Message file sp1<lang>.msb not found SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory`

Sure, but if you try to execute a script from terminal as well you get this error, If I understood you correctly.

**Comment by rygo18** [comment]
Terminal is running fine in all scenarios. 
From this command;
echo exit | sqlplus user/password%@server/db @/Users/my_file.pak

I got this;
![image](https://user-images.githubusercontent.com/6289751/68955250-816f7480-07bd-11ea-93bf-1a47ba711629.png)
