### ISSUE TITLE
Multi- Schema - Create source from DB

### ISSUE THREAD

**Issue by jowkeen** [mickeypearce/oradew-vscode#33]
Hi, how are you? 
First of all i need to congratulate you for the great job developing this one, its awsome!

So, i have multiples schemas where i want to control, but, when a use de command Create source from DB only extract the objects from user DEV. I already tried to change the env and the user but its not effective.

I already read [Add multi-schema support](https://github.com/mickeypearce/oradew-vscode/pull/8)

**Comment by jowkeen** [comment]
Nevermint, i go it. Thanks and again, concrats!!!!

**Comment by mickeypearce** [comment]
I am fine. Thanks for asking... :) Feel free to add any suggestions, questions, issues, PRs.
