### ISSUE TITLE
Problems with uppercase file extensions using Windows

### ISSUE THREAD

**Issue by true-hb** [mickeypearce/oradew-vscode#35]
Unfortunately we have almost any sql-source in our repository with an uppercased File-Extention, e.g. MYPACKAGE-body.SQL. 
Because of this I don't see the "Run Current File As Script (F5)" Button. I can't find even no way to configure this with something like 
	"source.input": ["./**/*.SQL"]

I'm using VSCode 1.46.1 under Windows 10

**Comment by mickeypearce** [comment]
I will add case insensitivity to path matching...

**Comment by true-hb** [comment]
Fine!
