### ISSUE TITLE
Compatibility for Dblink definitions and Apex applications

### ISSUE THREAD

**Issue by yevon** [mickeypearce/oradew-vscode#39]
It would very nice adding compatibility for more oracle db types and oracle apex applications support. The applications could be exported as one file in a .sql file, and separated by application components at the same time, pages, plugins etc:

This would be the function that could be used for doing so:
https://docs.oracle.com/en/database/oracle/application-express/20.1/aeapi/APEX_EXPORT.html#GUID-6A4628A6-9F86-4394-9938-87A7FFFC7BC8

**Comment by yevon** [comment]
I have implemented the Apex application export. Should I fork the project for making changes? Or I can just publish them to a branch if you give me permission to?

**Comment by yevon** [comment]
I put my initial changes in a fork:

https://github.com/yevon/oradew-vscode

The APEX application import is working nicely, but I don't know how to execute the result as script by default when you hit the "Compile" option,  instead of as sentence. Now it tries to execute it as a DDL and fails.

![image](https://user-images.githubusercontent.com/121157/96377178-04ded600-1184-11eb-9414-546a222bf1c7.png)

**Comment by mickeypearce** [comment]
> I have implemented the Apex application export. Should I fork the project for making changes? Or I can just publish them to a branch if you give me permission to?

Great! Just open a Pull Request and then we can merge your changes from fork to master.

**Comment by mickeypearce** [comment]
> I put my initial changes in a fork:
> 
> https://github.com/yevon/oradew-vscode
> 
> The APEX application import is working nicely, but I don't know how to execute the result as DDL by default when you hit the "Compile" option, instead of as script. Now it tries to execute it as a DDL and fails.
> 
> ![image](https://user-images.githubusercontent.com/121157/96377178-04ded600-1184-11eb-9414-546a222bf1c7.png)

Compile unfortunately compiles only one sentence, to compile a script you have to Run as a Script (sqlcl)(icon next to Compile or F5 shortcut)
