### ISSUE TITLE
Open selected package in new tab (import selected object)

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#4]
Hi,
is possible to open in new tab a selected (ctrl+click) package that is written in a file.sql?
It is usefull with plsql-language.

Thanks

**Comment by mickeypearce** [comment]
Do you mean when you click on procedure for example PCK_1.my_procedure1 that now opens inside opened editor?

**Comment by Danieleeee** [comment]
If I have a procedure PKG2.pippo(), opened in the editor, where is written "PCK_1.my_procedure1" (package PCK_1 is not present in my work area). 
If I click on "PCK_1.my_procedure1", you download it fron DB in my workarea and open it inside opened editor.

**Comment by mickeypearce** [comment]
Import of a selection (selected object) could be done. Not sure about Ctrl+click as this happens in separate extension.

**Comment by Danieleeee** [comment]
It works.
Is possible download selected package in current folder? 
Auto-open it in new tab? 
Select if I whant header or body only?

Thanks

**Comment by mickeypearce** [comment]
No, actually I can't see the point. 
But you can use this command on all types of DB objects. Try tables for examples, itd. :smile:
