### ISSUE TITLE
Run as Script hangs for a few minutes

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#40]
Hi Mickeypearce,
I noticed that when I launch a file as script (f5), it freezes for a few minutes.
The same file launched with SQLPlus (Oracle) is executed instantly.
Is there any configuration to do or is it the extension that takes time to run the script?

Thanks

**Comment by mickeypearce** [comment]
Hi @Danieleeee.
No, usually it runs quite fast in my case, it definetely shoudn't take few minutes. But at the end it succefully compiles or it hangs?
Can you provide a printscreen? Thanks

**Comment by Danieleeee** [comment]
At the end it work fine.
Now it's faster. I don't know why....
Thanks.

**Comment by Danieleeee** [comment]
it works properly
