### ISSUE TITLE
Windows econding UTF8 problem

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#42]
Hi,
I have a package that if I run as a script (f5) does not give errors.
If I only run the final part (Run Selected statement) of the package, where the grants are, I get errors.

![image](https://user-images.githubusercontent.com/22749175/96842847-d6941b80-144d-11eb-9178-60c8a998ac71.png)

![image](https://user-images.githubusercontent.com/22749175/96843012-178c3000-144e-11eb-8092-ed2c64d04e00.png)

I have similar errors if I don't set the correct econding (utf-8)

**Comment by mickeypearce** [comment]
Hi, do you use sqlplus or sqlcl?

**Comment by Danieleeee** [comment]
sqlplus

**Comment by Danieleeee** [comment]
If you can I suggest you always force encoding on utf-8 with sqlplus. 
It is the only one who works correctly.

**Comment by mickeypearce** [comment]
Take a look at https://github.com/mickeypearce/oradew-vscode/issues/28#issuecomment-547831047 and followed comments.

**Comment by Danieleeee** [comment]
It doesn't solve my problem.
There is a bug with running the selection.
I created a file with this code. 

``` sql
GRANT EXECUTE ON CONF_SET_VAL_TIPI_CONN_SVI TO NETAINF;
GRANT EXECUTE ON CONF_SET_VAL_TIPI_CONN_SVI TO SIU;
```

If I run it with f5 (run as script) it works, with Run Selected Statement, no.
If I delete only one of the two lines, the execution is performed correctly, with both lines not.

**Comment by Danieleeee** [comment]
It appears that it cannot execute the two selected lines. If I select only one, it works.

**Comment by mickeypearce** [comment]
Correct. A command like "Run Selected statement as a Script" is missing or a proper parser to compile multi-statement code.

**Comment by Danieleeee** [comment]
Hi,
for the problem with utf8 encoding there is no solution (https://github.com/mickeypearce/oradew-vscode/issues/42#issuecomment-714358311).
My oracle DB doesn't use utf8 encoding, but sqlplus uses it instead.
I tried to enter this configuration but nothing changes:
"oradew.envVariables": {
        "NLS_LANG": "ITALIAN_ITALY.WE8MSWIN1252",
    }

**Comment by mickeypearce** [comment]
Have you tried setting "source.encoding" to "win1252"? Import object again after that to correctly encode it. This is what I use.

**Comment by Danieleeee** [comment]
the encoding of the file is correctly windows1252, like Oracle configuration.
when launched to DB from sqlplus, UTF8 encoding is always applied and special characters such as this § are not encoded correctly.
are you sure that the parameterization "oradew.envVariables" is taken correctly?

**Comment by Danieleeee** [comment]
Is there no way to tell sqlplus not to apply UTF8 encoding, but Windows1252?

**Comment by mickeypearce** [comment]
I am not sure, I thought this was the case with setting nls_lang variable based on a user's comment, but I don't use it. I use win1250 encoded files to run to win1250 DB and it works, but I also have win1250 default lang on my OS system, which I think is the encoding that sqlplus applies. I guess in your case default OS encoding is UTF-8.
What about using UTF-8 encoded files? Is there a way you normally do to run a file with just sqlplus that works for you?

**Comment by Danieleeee** [comment]
The system language is ITALIAN_ITALY.WE8MSWIN1252
The files are launched correctly on the DB, not by execution error. But if they are then opened, if there are special characters in some comments or strings, they are badly coded.

**Comment by mickeypearce** [comment]
Hmm. Check also the vscode encoding in which the file is open - in the right bottom corner of status panel.

**Comment by Danieleeee** [comment]
![image](https://user-images.githubusercontent.com/22749175/98788041-926aba00-2400-11eb-82d7-3c8307884bbe.png)

**Comment by Danieleeee** [comment]
So you launch with sqlplus a file written with win1250 encoding, on an Oracle DB with NLS_CHARACTERSET = win1250 and the special characters like this "§" are not altered?

**Comment by mickeypearce** [comment]
That's right, I use many ČŠŽ in comments and other "strange" chars. My Win OS codepage is also 1250. I use sqlcl now but it worked with sqlplus also. Have you tried running files encoded in UTF-8?

**Comment by Danieleeee** [comment]
it seems the problem is in Oracle's charset, other than UTF8

**Comment by mickeypearce** [comment]
That shouldn't be the case, my charset on DB is also .WE8MSWIN1250.
Take a look at: https://stackoverflow.com/questions/42899387/oracle-sqlplus-execute-files-of-different-encoding maybe you will got some idea.

**Comment by Danieleeee** [comment]
It seems a problem related to machines that use Windows.
You should fix this by placing this code before the call to SQLPlus

```
C:\>chcp 1252
Active code page: 1252

C:\>set NLS_LANG=.WE8MSWIN1252
```

**Comment by Danieleeee** [comment]
In my case just give:
chcp 1252

**Comment by Danieleeee** [comment]
Can you create a parameter that makes me enter "chcp" before executing the sql code?

**Comment by mickeypearce** [comment]
https://github.com/mickeypearce/oradew-vscode/issues/28#issuecomment-549284560

Take a look at this comment. You create a sql.bat file and then set setting "oradew.sqlcli": "sql.bat"...

**Comment by Danieleeee** [comment]
ok, thanks.
If anyone wants to implement automatically, these are the two configurations to be given depending on whether you are using windows1252 or UTF8:
```
- windows1252
chcp 1252
set NLS_LANG = .WE8MSWIN1252
- UTF8
chcp 65001
set NLS_LANG = .UTF8
```

**Comment by Danieleeee** [comment]
I created a bat with this but it doesn't work. the plsql instruction appears to be executed in a different session.
bat file:
```
chcp 1252
set NLS_LANG = .WE8MSWIN1252
sqlplus UTE/PASS@DBNAME @"File.sql"
```

**Comment by Danieleeee** [comment]
if I set this bat, Oradew ask me user and password:
```
chcp 1252
set NLS_LANG = .WE8MSWIN1252
sqlplus
```

**Comment by mickeypearce** [comment]
Write 
Sqlplus %*
As in example so that parameters are passed through...

**Comment by Danieleeee** [comment]
ok, thanks.
Whit this bat it works:
```
chcp 1252 
set NLS_LANG=.WE8MSWIN1252
sqlplus %*
```

**Comment by mickeypearce** [comment]
This a workaround to pass variables to executable.  If you are satisfied consider adding a star to this project.

**Comment by Danieleeee** [comment]
because of you.
star added ;)

**Comment by Danieleeee** [comment]
Note that this solution does not work in the "compile current file" command, only in "Run ad Script (f5)"

**Comment by mickeypearce** [comment]
> Have you tried setting "source.encoding" to "win1252"? Import object again after that to correctly encode it. This is what I use.

Yes, compile task uses different method. chcp doesn't have any means here as node-oracledb compiles always in UTF-8. Setting "source.encoding" parameter means that oradew first decode file content from desired encoding to UTF-8 before compile.

**Comment by Danieleeee** [comment]
the problem is that they are always executed in UTF8.
It gives problems with the code page of the machine, if we are on windows and the file we are executing is not written in UTF8.
if you have a windows machine you can give it a try.

**Comment by mickeypearce** [comment]
I use it all the time and it works as I explained in the comment above. Have you tried exporting existing object from db, then adding some comments and compile again?

**Comment by Danieleeee** [comment]
No, I'm always working with the same file written in Windows1252. 
If I compile it gives problems with the coding, if I run it as a script no because I use the bat with chcp 1252.

**Comment by mickeypearce** [comment]
Can you send an example file so I can reproduce?

**Comment by Danieleeee** [comment]
I can't attach a file.sql so i write it here.

``` sql
CREATE OR REPLACE PACKAGE TEST_PCK AS

  v_test   varchar2(100):= '§';
 
END TEST_PCK;
/
```
Put it in a file with windows1252 encoding.
Run the Oradew "Compile Current File" command.
If the DB has Windows1252 encoding, you will not correctly see the '§' character.
Processing is launched from a Windows 10 machine

**Comment by mickeypearce** [comment]
Strange. NLS_LANG on my DB is .EE8MSWIN1250, I made a file encoded in Windows 1252 exactly as you suggested, compiled, checked on DB and it is '§'.
I have `"source.encoding": "win1250",` in `oradewrc.json` file, if I remove that, I get '?' instead of '§' on DB.
I don't have set any environment variables for NLS_LANG with "oradew.envVariables" or anywhere else...

**Comment by Danieleeee** [comment]
yes, if i use oradewrc.json it works.
Thanks

**Comment by mickeypearce** [comment]
Finally! :)

**Comment by Danieleeee** [comment]
Last thing, because when I import a package it writes: "CREATE OR REPLACE **EDITIONABLE** PACKAGE BODY".
how do i delete "EDITIONABLE"?

**Comment by mickeypearce** [comment]
This has to do with your database configuration - editions. I am not very familiar with this topic.

You can customize object DDL that is imported with oradewrc setting: `import.getDdlFunction` in a way that you write your own function to import objects...

**Comment by mickeypearce** [comment]
@Danieleeee , I closed this issue, feel free to open a new one if you have more questions, bugs, etc.
