### ISSUE TITLE
problems importing packages from the DB

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#44]
When I import a package from the DB, VSCode doesn't handle the word EDITIONABLE.
![image](https://user-images.githubusercontent.com/22749175/99397817-d881bb00-28e3-11eb-8f82-f7208a049bb4.png)

es. CREATE OR REPLACE EDITIONABLE PACKAGE UTE.PIPPO

The word is correct and the toad recognizes it. If used in VScode it fails to process package symbols.
Maybe it depends on the plsql extension, but would it be possible to remove it from the package import so as not to create errors?

Another problem, when I import a package, the "/" terminator is not placed at the end. 
Would it be possible to have it inserted automatically?

Thanks.

**Comment by mickeypearce** [comment]
@Danieleeee , Oradew uses  `DBMS_METADATA.get_ddl` function to import objects by default. This functionality can be customized with setting `"import.getDdlFunction"` in `oradewrc.json` in a way that you write your own function on DB that will be used by Oradew to import objects. This function should have 3 parameters - first 3 paramaters of `DBMS_METADATA.get_ddl` (example bellow).

To add a terminator at the end of each imported object you could make a function on your DB as follows, for example:
```sql
FUNCTION my_get_ddl (
  object_type         IN VARCHAR2,
  name                IN VARCHAR2,
  schema              IN VARCHAR2 DEFAULT NULL
RETURN CLOB
is
begin
  -- transform parameter to add / terminator at the end
  DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
  -- call get_ddl to return object ddl
  return DBMS_METADATA.get_ddl(object_type, name, schema);
end;
```
and then add a property with  `"import.getDdlFunction": "my_get_ddl"` to your oradew project.

Similiarly you could eliminate "EDITIONABLE" from packages, if a transform parameter exists, otherwise replace with 
`replace('create or replace editionable', 'editionable', '')` or something similar as a last resort. :)

**Comment by Danieleeee** [comment]
I used your procedure inserted in the code generator, very useful.

``` sql
function getDdl(
    object_type IN VARCHAR2, 
    name IN VARCHAR2, 
    schema IN VARCHAR2 DEFAULT NULL
  ) return clob is
    l_clob    clob := NULL;
    l_clob_header clob := 'CREATE OR REPLACE ';
    l_name VARCHAR2(100) := name;
    l_object_type VARCHAR2(100) := case object_type 
      when 'PACKAGE_SPEC' then 'PACKAGE' 
      when 'PACKAGE_BODY' then 'PACKAGE BODY' 
      when 'TYPE_SPEC' then 'TYPE' 
      when 'TYPE_BODY' then 'TYPE BODY' 
      else object_type
    end;
  begin
  
    -- dbms_metadata.get_ddl doesn't return objects outside my home schema
    -- all_source does (?)
    -- this is why we are going down this path
    
    dbms_lob.createtemporary(l_clob,true);      
    if l_object_type in ('VIEW', 'TRIGGER', 'TABLE') then         
      /*for rec in (
        select text
        from all_views
        where
          view_name = l_name
          and owner = schema    
      )loop    
        l_clob := rec.text;
       end loop;  */
       -- too hard !! for now as these object has different headers
       l_clob := dbms_metadata.get_ddl(l_object_type, name, schema);
    else
      for rec in (
        select text, line
        from all_source
        where
        name = l_name
        and owner = schema
        and type = l_object_type
        order by line      
      )loop      
        if rec.line = 1 then        
          --Add "create or replace" and schema
          --\s* - white spaces  
          l_clob := REGEXP_REPLACE (rec.text, '^(' || l_object_type|| '\s*)', l_clob_header || l_object_type|| ' "' || schema || '".', 1, 0, 'i'); 
          --Add " to object name, if it doesn't exists already
          --  1, 0,'i' - case insensitive
          l_clob := REGEXP_REPLACE (l_clob, '"?' || l_name || '"?', '"' || l_name || '"', 1, 0, 'i');         
        else
          dbms_lob.writeappend(l_clob, length(rec.text), rec.text);
        end if;
      end loop;    
    end if;
    dbms_lob.writeappend(l_clob, length('/'), '/');
    return l_clob;
  end getDdl;
```

**Comment by mickeypearce** [comment]
Ow, I forgot about this one!
