### ISSUE TITLE
Encoding problem in SQL-Statements

### ISSUE THREAD

**Issue by true-hb** [mickeypearce/oradew-vscode#50]
I could fix the encoding problem in packages with `"package.encoding": "win1252"`, but in simple SQL-Statements I still got a problem.

For testing I created a script sqlplus\test_encoding-table.SQL
```
--DROP table test_encoding;
CREATE TABLE test_encoding
AS SELECT 'ÄÖÜ-äöüß-€' AS umlaute FROM DUAL;
SELECT * FROM test_encoding;
```
The ouput is
```
> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.26\dist\oradew.js run --env RES_TEST --file D:\git\resus\datenbank\sqlplus\test_encoding-table.SQL --user <Auto> <

Success => RESUS@RES_TEST $D:\git\resus\datenbank\sqlplus\test_encoding-table.SQL
=============================== STDOUT ===============================
Table created.


UMLAUTE
----------
???-????-?

No errors.
```

When I select on this table with SQL*Plus I see
```
SQL> SELECT * FROM test_encoding;

UMLAUTE
----------
¿¿¿-¿¿¿¿-¿
```

When I run the same script using sqlplus, I got no problem.

this is my oradew.json:
```
{
	"source.input": ["./**/*.sql"],
	"source.encoding": "win1252",
	"source.pattern": {
		"packageSpec": "./packages/{object-name}-spec.sql",
		"packageBody": "./packages/{object-name}-body.sql",
		"trigger": "./trigger/{object-name}-trigger.sql",
		"views": "./views/{object-name}-view.sql",
		"table": "./sqlplus/{object-name}-table.sql"
	},
	"package.encoding": "win1252",
	"compile.warnings": "NONE",
	"compile.force": true,
	"compile.stageFile": false,
	"import.getDdlFunction": "dbms_metadata.get_ddl"
}
```

and settings.json is still the same as in #49
```
	"files.encoding": "windows1252",
	"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
	"terminal.integrated.shellArgs.windows": "/k chcp 1252",
	"oradew.envVariables": {
		"NLS_LANG": "GERMAN_GERMANY.WE8MSWIN1252"
	}
```

**Comment by mickeypearce** [comment]
I added a setting to customize DB CLI command:

`"oradew.cliCommand": "chcp 1250 && exit | sql -S ${connString} @\"${filename}\""`  would change code page to 1250 (`chcp 1250`) before executing `sql`...

For `sqlplus` is a bit different as it also includes `show errors`:
``"oradew.cliCommand": "chcp 1250 && (echo connect ${connString} && echo start ${filename} && echo show errors) | sqlplus -S /nolog"`

Some additional info can be found in [wiki#6](https://github.com/mickeypearce/oradew-vscode/wiki#6).

**Comment by true-hb** [comment]
oradew.cliCommand works for me when I add the `set NLS_LANG` command:
```
"oradew.cliCommand": "chcp 1252 && set NLS_LANG=.WE8MSWIN1252 && (echo connect ${connString} && echo start ${filename} && echo show errors) | sqlplus -S /nolog"
```

Now I'm satistfied 👍

**Comment by mickeypearce** [comment]
Great! There was a problem with `envVariables` , it is now also fixed and will be available in the next release.
