### ISSUE TITLE
Initialize Workspace not working

### ISSUE THREAD

**Issue by MaikMichel** [mickeypearce/oradew-vscode#56]
Hi,

when using "Initialize Workspace" in an empty folder I'm prompted to create a task.json with default options. What am I doing wrong?
See screen recording...
![screen-rec-rdp](https://user-images.githubusercontent.com/12570539/114604883-c12fd980-9c99-11eb-9dfc-5923b43537ea.gif)

Thank you

**Comment by mickeypearce** [comment]
Hi, 
thanks for reporting.

No, that "Configure a task" prompt after you ran "Initialize Workspace" shouldn't come up. I have difficulty in reproducing this, but I am on Windows. What OS do you use? Thanks for info.

**Comment by MaikMichel** [comment]
Hi ,


```
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

this is taken from the about panel.

**Comment by mickeypearce** [comment]
I have exact same configuration, including OS version. The only difference is the VS Code version:

`Version: 1.55.2 (system setup)`

but I doubt that causes the problem.

For some reason the extension didn't succeed to register oradew tasks. Can you please check with command `Tasks: Configure Task`. You should see:

![image](https://user-images.githubusercontent.com/1925433/114828267-fcc9c100-9dc9-11eb-883e-8038e6963f76.png)

**Comment by mickeypearce** [comment]
Please check if there are any errors in `Oradew Auto Detection` output chanel (`Output` panel). Thanks a lot.

**Comment by MaikMichel** [comment]
There is no Oradew* channel at all. When I run `Command: Configure Task ` and no tasks.json is present I get prompted with following screen:
![image](https://user-images.githubusercontent.com/12570539/114921919-5ca48400-9e2b-11eb-8d0f-d6cb7d041390.png)

Otherwise, if I have my own tasks.json present, I get only my options displayed.
I have tried to get it working by disabling all other extensions, but no success...

**Comment by mickeypearce** [comment]
Do you have `"task.autoDetect": "off"` in your user settings? That should be on so oradew can register tasks...

**Comment by MaikMichel** [comment]
Oh ha, thanky you. I have switched autoDetect to off a year ago... Now it works!!!

**Comment by mickeypearce** [comment]
You are welcome! Star the project if you will like it. :)
