### ISSUE TITLE
Error while trying to retrieve text for error ORA-01804

### ISSUE THREAD

**Issue by rpietka** [mickeypearce/oradew-vscode#62]
When I try to compile an object I get a "1/1 ERROR Error while trying to retrieve text for error ORA-01804" message

**Comment by yevon** [comment]
Can you check this?

https://stackoverflow.com/questions/12837811/error-while-trying-to-retrieve-text-for-error-ora-01804

**Comment by rpietka** [comment]
Thank you for your help. the link you provided helped. Only the variables had to be entered in the plugin configuration.

**Comment by mickeypearce** [comment]
Can you just post what you added to configuration to solve the issue..  thanks.
