### ISSUE TITLE
Support latest version of node

### ISSUE THREAD

**Issue by yevon** [mickeypearce/oradew-vscode#64]
What changes are needed in order to support latest versions of node js? Is there any dependency thats needs that version?

**Comment by mickeypearce** [comment]
Upgrade node-oracledb to 5.1.0 https://github.com/oracle/node-oracledb/releases/tag/v5.1.0 , as it has prebuild bins for node 10, 12, 14 or later. Maybe it will cause some breaking changes because of upgrade. If everything works, that should be it.

**Comment by mickeypearce** [comment]
I upgraded oracledb to 5.1.0 and only few other libs for now as major upgrade of all libs require a bit more work.. Let me know if it works node 16.

**Comment by mickeypearce** [comment]
5.2.0 doesn't include binaries for node 10, 12 but only for node 14 and later. I don't know, I thought maybe this would be an issue for some users....

**Comment by mickeypearce** [comment]
Actually 5.2.0^ is for Node 12 and later, i misread as 14+, so my bad. We can update to latest version no problem...
