### ISSUE TITLE
Problem importing when object has "SQL" in the name

### ISSUE THREAD

**Issue by palewolf** [mickeypearce/oradew-vscode#70]
Importing objects fail when the object contains "SQL" somewhere in the name. In a concrete example, let's imagine a FUNCTION named "UpdateMysqlFromOracle". When trying to import that function (doesn't matter if via Create source from DB or Import current file) the following error appears:

```
[16:03:45] Starting 'import'...
ORA-31603: object "UPDATEMFROMORACLE" of type FUNCTION not found in schema "SCHEMA_NAME"
ORA-06512: at "SYS.DBMS_METADATA", line 6731
ORA-06512: at "SYS.DBMS_SYS_ERROR", line 105
ORA-06512: at "SYS.DBMS_METADATA", line 6718
ORA-06512: at "SYS.DBMS_METADATA", line 9734
ORA-06512: at line 1
[16:03:46] Finished 'import' after 965 ms
```

Notice that from `MYSQL`, `YSQL` is stripped from the name while the `M` remains.

Happens with all procedures and functions that follow a similar pattern.

I think the problem is caused in this section of the extension's code:
https://github.com/mickeypearce/oradew-vscode/blob/63727842aebfa67253d0d5f50b1d37514881a3a1/src/cli/common/dbobject.ts#L135

More precisely, the `.sql` portion of the pattern is matched against M`ySQL` and ends up getting stripped.

**Comment by mickeypearce** [comment]
Hey, you are right. Good find.
The second part ( `objectSplit[1]`) shouldn't be treated as a regexp but just as a regular string ('.sql'). If you are up for fixing this, feel free to open pull request. Your help will be very appreciated..
